#!/bin/bash
echo "🔥 COMPLETE FIREBASE SETUP 🔥"
echo "============================="
echo ""
echo "STEP 1: Enable Firebase Auth"
echo "   - Go to: https://console.firebase.google.com/"
echo "   - Project: 'elderguard-project'"
echo "   - Authentication → Sign-in method → Email/Password → ENABLE"
echo ""
echo "STEP 2: Get Web Config"
echo "   - Project Settings → Your apps → Web app"
echo "   - Register: 'ElderGuard-Web'"
echo "   - Copy config to src/firebase/client.js"
echo ""
echo "STEP 3: Get Service Account Key"
echo "   - Project Settings → Service accounts"
echo "   - Generate new private key"
echo "   - Save as backend/service-account-key.json"
echo ""
echo "STEP 4: Create Users"
echo "   Run: node create-real-firebase-users.js"
echo ""
echo "STEP 5: Start Servers"
echo "   Backend: cd backend && npm start"
echo "   Frontend: cd .. && npm run dev"
echo ""
echo "STEP 6: Test Login"
echo "   Use: caregiver@elderguard.com / Caregiver123!"
echo ""
read -p "Press enter when you've completed STEP 1-3..."
